#Operadores Arimetricos
numero1 = 77
numero2 = 44 # = operador de asignacion

resta = numero1 - numero2
suma = numero2 + numero2
division = numero2 / numero1
multipliacion = numero1 * numero2
resto = numero1 % numero2
#resto sirve para sacar el resto de la division 

print("*************Calcualdora****************")
print(f"La resta es: {resta}")
print(f"la suma es: {suma}")
print(f"la division es: {division}")
print(f"la multiplicacion es: {multipliacion}")
print(f"el resto de la division es: {resto}")





