"""
Programacion orientada a objeto 
es un paradigma de programacion 
es una forma de ver la programacion y una forma de programar 
es como ver un objeto de la vida real y ver sus propiedades ya tributos 
FUNDAMENTO PRINCIPALES DE LA PROGRAMACION ORIENTADA A OBJETOS 
CLASES : LAS CLASES SON AQUELLOS QUE NOS VAN A DEFINIR QUE PROPIEDADES Y QUE COSAS VA A HACER 
NUESTRO OBJETO FINAL ES COMO UN MOLDE 
EJEMPLO : UN COCHE/ AUTO 

ATRIBUTOS/PROPIEDADES :
SON CADA UNA DE LAS PIEZAS O CARACTERISTICAS QUE VAN A FORMAR EL COCHE 

MÉTODOS/CLASE:
SON LAS ACCIONES QUE PUEDE HACER NUESTRO OBJETO 
EJEMPLO:ARRANCAR / ACELERAR / PONER EN MARCHA 
BASICAMENTE SON LAS COSAS QUE PUEDE HACER NUESTRO OBJETO 
PODEMOS DARLE ATRIBUTOS A NUESTRA CLASE 

ABSTRACCIÓN:
VAMOS A PODER UTILIZAR UN OBJETO SIN NECESIDAD DE CONOCER EL FUNCIONAMIENTO INTERNO QUE TIENE 
ESE OBJETO.
LA CLASE PUEDE FUNCIONAR PARA CUALQUIER TIPO DE OBJETO Y ASI USARLA PARA OBJETO SIMILARES 
PODER AGILIZAR MUCHO MAS EL TRABAJO

HERENCIA:
LAS CLASES PUEDE HEREDAR UNA DE OTRA PROPIEDADES Y METODOS 
EN CADA CLASE PUEDO IR HEREDANDO DE LA CLASE PADRE Y ASI PODER IR AÑADIENDO
PROPIEDADES EN CADA CLASE HIJA 

MODULARIDAD:
BASICAMENTE PUEDO DIVIDIR MI APLICACION EN PARTES MAS PEQUEÑAS 
MAS CONCRETAS QUE SE DEDIQUEN A ALGO MAS ESPECIFICO 
EJEMPLO DIFERENTES CLASES QUE SE DEDIQUEN A HACER COSAS DISTINTAS 

OCULTACIÓN:
ESTO SIGNIFICA QUE CADA OBJETO TIENEN SUS DATOS EN CONCRETO 
SOLO DEBEN MODIFICARSE DENTRO DE LA CLASE 



"""