"""
Ejercicio 4
Pedir numeros al usuario y hacer todas las funciones basicas de una calculadora
y motrarlo por pantalla 
"""


numero1 = int(input("introduce el primer numero:"))
numero2 = int(input("introdue el segundo numero: "))

print("###Calculadora###")
print("Suma : " + str(numero1+numero2))
print("Resta : " + str(numero1-numero2))
print("Multiplicación : " + str(numero1*numero2))
print("Division : " + str(numero1/numero2))