"""
Ejercicio 3
Escribir un programa que muestre los cuadrados 
(Un numero multiplicado por si mismo) de los 60 primeros numeros 
naturales. Resolverlo con el bucle for y con el bucle While
"""

#While 
"""
contador = 0
while contador <= 60:
    
    cuadrado = contador*contador
    print(f"El cuadrado de {contador} es {cuadrado}")

    contador += 1
    """

#FOR


for numero in range(65):
    cuadrado = numero*numero 
    print(f"el cuadrado de {numero} es {cuadrado}")
    # JUANCHO DEL FUTURO SE TE HACE MAS PROLIJO Y ENTENDIBLE EL BUCLE "FOR" EL "WHILE" SON MUCHAS MAS LINEAS DE CODIGO
    
